"""Constants cho Chronic Care Phase 3A shadow mode."""
from __future__ import annotations

ENVIRONMENT = "synthetic_shadow"
MODULE_NAME = "Chronic Care Coordination Module"
DISPLAY_NAME = "Mô-đun điều phối quản lý bệnh mạn ngoại trú"

PROGRAM_CODES = {
    "HTN_PROGRAM",
    "T2D_PROGRAM",
    "DYSLIPIDEMIA_PROGRAM",
    "CARDIOMETABOLIC_RISK_PROGRAM",
    "POLYPHARMACY_REVIEW_PROGRAM",
    "POST_DISCHARGE_REVIEW_PROGRAM",
}

RISK_LABELS = {"GREEN", "YELLOW", "RED", "UNASSESSED"}
RISK_DRAFT_STATUSES = {"DRAFT", "PENDING_REVIEW", "APPROVED_FOR_SHADOW", "REJECTED"}
CARE_PLAN_DRAFT_STATUSES = {"DRAFT", "PENDING_REVIEW", "APPROVED_FOR_SHADOW", "REJECTED", "ARCHIVED", "BLOCKED"}

TASK_TYPES = {
    "SCHEDULE_FOLLOW_UP",
    "VERIFY_APPOINTMENT_STATUS",
    "REQUEST_PHYSICIAN_REVIEW",
    "MEDICATION_LIST_REVIEW",
    "LAB_RESULT_REVIEW",
    "CARE_PLAN_REVIEW",
    "POST_DISCHARGE_REVIEW",
    "QUALITY_DATA_CHECK",
    "REVIEW_OVERDUE_CASE",
    "REVIEW_RED_FLAG_INPUT",
}

REVIEW_TYPES = {
    "INITIAL_REVIEW",
    "FOLLOW_UP_REVIEW",
    "OVERDUE_REVIEW",
    "POST_DISCHARGE_REVIEW",
    "MEDICATION_RECONCILIATION_REVIEW",
    "LABORATORY_REVIEW",
    "CARE_PLAN_REVIEW",
    "RISK_REVIEW",
}

TIMELINE_EVENT_TYPES = {
    "PROGRAM_ENROLLED",
    "REVIEW_CREATED",
    "TASK_CREATED",
    "TASK_COMPLETED",
    "RISK_DRAFT_CREATED",
    "RISK_DRAFT_REVIEWED",
    "CARE_PLAN_DRAFT_CREATED",
    "CARE_PLAN_DRAFT_APPROVED",
    "FOLLOW_UP_OVERDUE",
    "APPOINTMENT_STATUS_CHANGED",
    "LAB_REVIEW_REQUIRED",
    "MEDICATION_REVIEW_REQUIRED",
    "POST_DISCHARGE_FLAGGED",
    "ESCALATION_CREATED",
}

RISKY_FLAGS_MUST_STAY_FALSE = {
    "v7_clinical_release",
    "v7_patient_education_export",
    "v7_emr_write",
    "v7_production_pathway",
    "v7_auto_apply_recommendations",
}
