"""Hệ bền với đường mạng thay đổi (VPN bật/tắt, máy chủ VPN đổi) — 01/10/2026, bác sĩ yêu cầu «giải quyết triệt để».

Bốn mảnh, đều CHỈ ĐO và BÁO (không đổi PASS/PARTIAL/FAIL):
1. HttpClient gắn nhãn tầng mạng ĐẦU `last_error`: trang chặn CloudFront (đo thật ECDC/EMA 01/10), NCBI gắn cờ IP,
   proxy, hết giờ MỞ kết nối (WHO IRIS), kết nối hỏng, DNS, TLS — thông điệp ngoại lệ ném ra GIỮ NGUYÊN.
2. `summarize_source_health` gom các nhãn đó vào `loi_duong_mang` — không tham gia health/status.
3. `app/utils/mang.py`: dấu vân đường mạng tại máy, ba trạng thái, không lộ IP máy chủ VPN/giá trị proxy.
4. `nguon_hong_keo_dai`: nguồn «unavailable» nhiều lượt live liền, trải ≥ 7 ngày (ca NEJM 07→29/09 không ai thấy).
Kèm công cụ `tools/do_mang_nguon.py` (phân loại CÙNG bộ nhận diện). Offline hoàn toàn: phiên HTTP giả, lệnh hệ
thống giả.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import pytest
import requests

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.config import settings  # noqa: E402
from app.services import ingestion as ing  # noqa: E402
from app.services import nguon_hong_keo_dai as nhkd  # noqa: E402
from app.services.ingestion import summarize_source_health  # noqa: E402
from app.utils import http as http_mod  # noqa: E402
from app.utils import mang  # noqa: E402
from app.utils.http import (  # noqa: E402
    DAU_CLOUDFLARE_CHAN,
    DAU_CLOUDFRONT_CHAN,
    DAU_DNS_HONG,
    DAU_KET_NOI_HET_GIO,
    DAU_KET_NOI_HONG,
    DAU_NCBI_CHAN,
    DAU_PROXY_CHAN,
    DAU_TLS_HONG,
    NHAN_DUONG_MANG,
    HttpClient,
    nhan_duong_mang_cua,
)

# Trang chặn CloudFront — cấu trúc đo thật 01/10/2026 (www.ecdc.europa.eu, www.ema.europa.eu qua VPN).
TRANG_CLOUDFRONT = ("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"><HTML><HEAD><TITLE>ERROR: The "
                    "request could not be satisfied</TITLE></HEAD><BODY><H1>403 ERROR</H1><H2>The request could not be "
                    "satisfied.</H2><HR noshade size=\"1px\">Request blocked.<BR clear=\"all\">Generated by cloudfront "
                    "(CloudFront)<BR clear=\"all\">Request ID: AbC123==</BODY></HTML>")
TIEU_DE_CLOUDFRONT = {"Server": "CloudFront", "X-Cache": "Error from cloudfront", "X-Amz-Cf-Id": "AbC123==",
                      "X-Amz-Cf-Pop": "FRA60-P14", "Via": "1.1 abc.cloudfront.net (CloudFront)"}
TRANG_CLOUDFLARE = ("<title>Attention Required! | Cloudflare</title><div id=\"cf-error-details\">"
                    "<span>Cloudflare Ray ID: <strong>8c1f</strong></span></div>")
URL = "https://www.ecdc.europa.eu/en/taxonomy/term/2942/feed"


class _PhanHoi:
    def __init__(self, status_code: int, text: str = "", headers: Any = None, url: str = URL) -> None:
        self.status_code, self.text, self.url = status_code, text, url
        self.headers = {} if headers is None else headers
        self.content = text.encode()

    def raise_for_status(self) -> None:
        if self.status_code >= 400:
            raise requests.HTTPError(f"{self.status_code} Client Error: Forbidden for url: {self.url}")

    def json(self) -> Any:
        return json.loads(self.text)


class _PhienGia:
    """Mỗi lần gọi trả phần tử kế tiếp của `chuoi` (phần tử cuối lặp lại); ngoại lệ thì ném."""

    def __init__(self, *chuoi: Any) -> None:
        self.chuoi, self.so_lan = list(chuoi), 0

    def request(self, method, url, params=None, timeout=None, **extra):
        muc = self.chuoi[min(self.so_lan, len(self.chuoi) - 1)]
        self.so_lan += 1
        if isinstance(muc, BaseException):
            raise muc
        return muc


@pytest.fixture(autouse=True)
def _khong_ngu_that(monkeypatch):
    monkeypatch.setattr(http_mod.time, "sleep", lambda s: None)
    monkeypatch.setattr(settings, "http_max_retries", 2)


def _client(*chuoi: Any) -> HttpClient:
    client = HttpClient(cache_ttl=0, min_interval=0)
    client.session = _PhienGia(*chuoi)
    return client


def _loi_cuoi(client: HttpClient, ngoai_le=Exception, url: str = URL, params: Optional[dict] = None) -> str:
    with pytest.raises(ngoai_le):
        client.get_text(url, params=params)
    return client.last_error


# ═════════════ 1. HttpClient — nhãn tầng mạng ═════════════

def test_trang_chan_cloudfront_duoc_gan_nhan_o_dau():
    loi = _loi_cuoi(_client(_PhanHoi(403, TRANG_CLOUDFRONT, TIEU_DE_CLOUDFRONT)), requests.HTTPError)
    assert loi.startswith(DAU_CLOUDFRONT_CHAN + " HTTPError: 403 Client Error")


def test_loi_403_cua_may_chu_goc_di_qua_cloudfront_khong_bi_gan_nhan():
    """Máy chủ nguồn đứng sau CloudFront: tiêu đề có `x-amz-cf-id`/`x-cache: Error…` nhưng thân là trang của nguồn."""
    tieu_de = {"Server": "Apache", "X-Cache": "Error from cloudfront", "X-Amz-Cf-Id": "x"}
    loi = _loi_cuoi(_client(_PhanHoi(403, "<h1>Forbidden</h1><p>You don't have permission</p>", tieu_de)),
                    requests.HTTPError)
    assert not loi.startswith("[") and "403 Client Error" in loi


def test_than_giong_cloudfront_nhung_khong_qua_cloudfront_khong_bi_gan_nhan():
    loi = _loi_cuoi(_client(_PhanHoi(403, TRANG_CLOUDFRONT, {"Server": "nginx"})), requests.HTTPError)
    assert DAU_CLOUDFRONT_CHAN not in loi


def test_trang_loi_cloudfront_khong_phai_403_khong_bi_gan_nhan():
    loi = _loi_cuoi(_client(_PhanHoi(404, TRANG_CLOUDFRONT.replace("403", "404"), TIEU_DE_CLOUDFRONT)),
                    requests.HTTPError)
    assert DAU_CLOUDFRONT_CHAN not in loi


def test_trang_cloudflare_van_mang_nhan_cloudflare():
    loi = _loi_cuoi(_client(_PhanHoi(403, TRANG_CLOUDFLARE, {"Server": "cloudflare", "CF-RAY": "8c1f"})),
                    requests.HTTPError)
    assert loi.startswith(DAU_CLOUDFLARE_CHAN + " ") and DAU_CLOUDFRONT_CHAN not in loi


def test_het_gio_mo_ket_noi_moi_lan_thu_gan_nhan_va_giu_nguyen_thong_diep_ngoai_le():
    """WHO IRIS 29/09: Source Log chỉ còn «Gọi API thất bại sau 4 lần» — mất kiểu lỗi."""
    client = _client(requests.exceptions.ConnectTimeout("HTTPSConnectionPool(host='iris.who.int'): Max retries"))
    with pytest.raises(RuntimeError) as ei:
        client.get_text("https://iris.who.int/oai/request")
    assert str(ei.value) == f"Gọi API thất bại sau {settings.http_max_retries} lần: https://iris.who.int/oai/request"
    assert client.last_error.startswith(DAU_KET_NOI_HET_GIO + " RuntimeError (lỗi cuối: ConnectTimeout): Gọi API")


@pytest.mark.parametrize("ngoai_le, nhan", [
    (requests.exceptions.ConnectionError("Failed to resolve 'iris.who.int' ([Errno 8] nodename nor servname "
                                         "provided, or not known)"), DAU_DNS_HONG),
    (requests.exceptions.ConnectionError("NameResolutionError: getaddrinfo failed"), DAU_DNS_HONG),
    (requests.exceptions.ConnectionError("[Errno 61] Connection refused"), DAU_KET_NOI_HONG),
    (requests.exceptions.ConnectionError("Connection aborted. RemoteDisconnected"), DAU_KET_NOI_HONG),
    (requests.exceptions.SSLError("certificate verify failed"), DAU_TLS_HONG),
])
def test_loi_van_chuyen_duoc_gan_dung_nhan(ngoai_le, nhan):
    client = _client(ngoai_le)
    assert _loi_cuoi(client, RuntimeError).startswith(nhan + " RuntimeError (lỗi cuối: ")


def test_het_gio_doc_phan_hoi_khong_phai_loi_duong_mang():
    """ReadTimeout: máy chủ ĐÃ nhận kết nối nhưng trả chậm — không gắn nhãn, chỉ ghi tên lớp lỗi cuối."""
    loi = _loi_cuoi(_client(requests.exceptions.ReadTimeout("Read timed out.")), RuntimeError)
    assert loi.startswith("RuntimeError (lỗi cuối: ReadTimeout): Gọi API thất bại")
    assert nhan_duong_mang_cua(loi) is None


def test_json_hong_khong_phai_loi_duong_mang():
    client = _client(_PhanHoi(200, "<html>không phải json</html>"))
    with pytest.raises(RuntimeError):
        client.get_json("https://api.example.org/x")
    assert not client.last_error.startswith("[") and "(lỗi cuối: JSONDecodeError)" in client.last_error


def test_proxy_tu_choi_theo_chinh_sach_gan_nhan_proxy_va_giu_thong_diep():
    loi_proxy = requests.exceptions.ProxyError("Unable to connect to proxy: Tunnel connection failed: 403 Forbidden")
    client = _client(loi_proxy)
    with pytest.raises(RuntimeError) as ei:
        client.get_json("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi")
    assert str(ei.value).startswith("Proxy thoát mạng của môi trường này TỪ CHỐI")
    assert client.last_error.startswith(DAU_PROXY_CHAN + " RuntimeError (lỗi cuối: ProxyError): Proxy thoát mạng")


def test_ncbi_chuyen_huong_misuse_gan_nhan_ncbi():
    ph = _PhanHoi(200, "<html>NCBI Error Access Denied</html>", url="https://misuse.ncbi.nlm.nih.gov/error/abuse.shtml")
    client = _client(ph)
    with pytest.raises(RuntimeError) as ei:
        client.get_json("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi")
    assert "NCBI đã CHẶN mạng này" in str(ei.value)
    assert client.last_error.startswith(DAU_NCBI_CHAN + " RuntimeError: NCBI đã CHẶN")


def test_ncbi_trang_chan_trong_than_gan_nhan_ncbi():
    ph = _PhanHoi(200, "<title>WWW Error Blocked Diagnostic</title>",
                  url="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi")
    client = _client(ph)
    with pytest.raises(RuntimeError):
        client.get_json("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi")
    assert client.last_error.startswith(DAU_NCBI_CHAN + " ")


def test_khoa_trong_url_van_bi_che_khi_co_ten_loi_cuoi():
    client = _client(requests.exceptions.ConnectTimeout("timeout ?api_key=BIMAT123&email=a@b.c"))
    loi = _loi_cuoi(client, RuntimeError, url="https://eutils.ncbi.nlm.nih.gov/x?api_key=BIMAT123")
    assert "BIMAT123" not in loi and "a@b.c" not in loi


def test_nhan_duong_mang_cua_chi_nhan_nhan_o_dau_chuoi():
    assert nhan_duong_mang_cua("[cloudfront-chan] HTTPError: 403") == "cloudfront-chan"
    assert nhan_duong_mang_cua("du_phong:openfda_enforcement sau lỗi nguồn chính: [cloudfront-chan] x") is None
    assert nhan_duong_mang_cua("[cloudfront-chanx] y") is None
    assert nhan_duong_mang_cua("[la-hoac] y") is None
    assert nhan_duong_mang_cua(None) is None
    assert {nhan_duong_mang_cua(n + " x") for n in NHAN_DUONG_MANG} == {n[1:-1] for n in NHAN_DUONG_MANG}


# ═════════════ 2. summarize_source_health — `loi_duong_mang` chỉ để NHÌN ═════════════

def _dong(nguon: str, status: str, so: int = 0, loi: Optional[str] = None) -> dict:
    return {"source": nguon, "status": status, "record_count": so, "error_message": loi}


def _bo_dong(gan_nhan: bool) -> List[dict]:
    def nhan(dau: str, loi: str) -> str:
        return f"{dau} {loi}" if gan_nhan else loi
    dong = [_dong(n, "ok", 5) for n in ("pubmed", "europepmc", "crossref")]
    # PubMed vừa có lần chạy được vừa có lần NCBI chặn: nhãn không được biến «degraded» thành «unavailable».
    dong += [_dong("pubmed", "error", 0, nhan(DAU_NCBI_CHAN, "RuntimeError: NCBI đã CHẶN mạng này"))]
    dong += [_dong(f"feed_g{i}", "ok", 3) for i in range(4)]
    dong += [_dong("feed_ecdc_threats", "error", 0, nhan(DAU_CLOUDFRONT_CHAN, "HTTPError: 403 Client Error: x")),
             _dong("feed_who_iris", "error", 0,
                   nhan(DAU_KET_NOI_HET_GIO, "RuntimeError (lỗi cuối: ConnectTimeout): x")),
             _dong("feed_bjgp", "error", 0, "HTTPError: 500 Server Error: x")]
    return dong


def _tong_hop(dong: List[dict]) -> dict:
    feeds = sorted({d["source"] for d in dong if d["source"].startswith("feed_")})
    return summarize_source_health(dong, expected_api_sources=["pubmed", "europepmc", "crossref"],
                                   expected_feed_sources=feeds, safety_enabled=False)


def test_loi_duong_mang_liet_ke_dung_nguon_va_kieu():
    h = _tong_hop(_bo_dong(gan_nhan=True))
    assert h["loi_duong_mang"] == {
        "feed_ecdc_threats": {"kieu": {"cloudfront-chan": 1}, "loi_duong_mang": 1, "loi": 1, "health": "unavailable"},
        "feed_who_iris": {"kieu": {"ket-noi-het-gio": 1}, "loi_duong_mang": 1, "loi": 1, "health": "unavailable"},
        "pubmed": {"kieu": {"ncbi-chan": 1}, "loi_duong_mang": 1, "loi": 1, "health": "degraded"},
    }
    assert h["sources"]["feed_bjgp"]["error_duong_mang"] == 0 and h["sources"]["feed_bjgp"]["kieu_duong_mang"] == {}


def test_nhan_duong_mang_khong_doi_trang_thai_hay_canh_bao():
    co, khong = _tong_hop(_bo_dong(gan_nhan=True)), _tong_hop(_bo_dong(gan_nhan=False))
    assert khong["loi_duong_mang"] == {}
    for khoa in ("status", "hard_fail_reasons", "warnings", "mirror_notices", "degraded_required_sources"):
        assert co[khoa] == khong[khoa], khoa
    assert {n: r["health"] for n, r in co["sources"].items()} == {n: r["health"] for n, r in khong["sources"].items()}


def test_nhan_tren_dong_khong_phai_loi_khong_duoc_dem():
    dong = [_dong("feed_x", "degraded", 2, f"{DAU_CLOUDFRONT_CHAN} chỉ là ghi chú"),
            _dong("feed_x", "skipped", 0, f"{DAU_CLOUDFRONT_CHAN} bỏ qua")]
    assert _tong_hop(dong)["loi_duong_mang"] == {}


# ═════════════ 3. Dấu vân đường mạng ═════════════

IP_MAY_CHU = "149.50.211.70"
SCUTIL_LIST = ('Available network connection services in the current set (*=enabled):\n'
               '* (Connected)      0A1B2C3D-0000-0000-0000-000000000000 VPN (com.kaspersky.ksec.bl.resolver) '
               '"Kaspersky VPN"                  [VPN:com.kaspersky.ksec.bl.resolver]\n')
SCUTIL_STATUS = ("Connected\nExtended Status <dictionary> {\n  IPv4 : <dictionary> {\n    InterfaceName : utun4\n"
                 f"    ServerAddress : {IP_MAY_CHU}\n  }}\n  LastStatusChangeTime : 09/30/2026 17:52:33\n"
                 f"  VPN : <dictionary> {{\n    RemoteAddress : {IP_MAY_CHU}\n  }}\n}}\n")


def _lenh_gia(bang: Dict[str, str]):
    def chay(lenh):
        return bang.get(" ".join(lenh[1:3]), "")
    return chay


def test_macos_qua_vpn_khong_lo_ip_may_chu():
    dv = mang.dau_van_mang(_lenh_gia({"--nc list": SCUTIL_LIST, "--nc status": SCUTIL_STATUS,
                                      "-n get": "   route to: default\n  interface: utun4\n"}), "darwin")
    assert dv["qua_vpn"] is True and dv["vpn_dang_noi"] == ["Kaspersky VPN"] and dv["tuyen_mac_dinh"] == "utun4"
    assert len(dv["may_chu_vpn"]) == 8 and dv["vpn_doi_trang_thai_luc"] == "09/30/2026 17:52:33"
    assert IP_MAY_CHU not in json.dumps(dv)
    assert mang.mo_ta_ngan(dv) == f"qua VPN «Kaspersky VPN» (tuyến utun4, máy chủ #{dv['may_chu_vpn']})"


def test_macos_ra_thang():
    dv = mang.dau_van_mang(_lenh_gia({"--nc list": "Available network connection services:\n",
                                      "-n get": "  interface: en0\n"}), "darwin")
    assert dv["qua_vpn"] is False and dv["vpn_dang_noi"] == [] and dv["may_chu_vpn"] is None
    assert mang.mo_ta_ngan(dv).startswith("ra thẳng, không qua VPN (tuyến en0")


def test_macos_khong_doc_duoc_tuyen_la_khong_do_duoc_khong_phai_khong_vpn():
    dv = mang.dau_van_mang(_lenh_gia({}), "darwin")
    assert dv["qua_vpn"] is None and dv["ghi_chu"]
    assert mang.mo_ta_ngan(dv).startswith("KHÔNG đo được")


@pytest.mark.parametrize("dong, ky_vong", [("default via 10.8.0.1 dev wg0 proto static", True),
                                           ("default via 192.168.1.1 dev eth0 proto dhcp metric 100", False),
                                           ("", None)])
def test_linux_doc_tuyen_mac_dinh(monkeypatch, dong, ky_vong):
    monkeypatch.setattr(mang.shutil, "which", lambda ten: "/usr/sbin/ip")
    dv = mang.dau_van_mang(lambda lenh: dong if lenh[1:4] == ["-o", "route", "show"] else "", "linux")
    assert dv["qua_vpn"] is ky_vong


def test_windows_chua_ho_tro_la_khong_do_duoc():
    dv = mang.dau_van_mang(_lenh_gia({}), "win32")
    assert dv["qua_vpn"] is None and "không đo được ≠ không có VPN" in dv["ghi_chu"]


def test_lenh_he_thong_nem_loi_khong_lam_hong_luot():
    def no(lenh):
        raise RuntimeError("scutil hỏng")
    dv = mang.dau_van_mang(no, "darwin")
    assert dv["qua_vpn"] is None and "RuntimeError" in dv["ghi_chu"]


def test_proxy_moi_truong_chi_ghi_co_khong_khong_ghi_gia_tri(monkeypatch):
    monkeypatch.setenv("HTTPS_PROXY", "http://nguoidung:MATKHAU@proxy.local:3128")
    dv = mang.dau_van_mang(_lenh_gia({"-n get": "  interface: en0\n"}), "darwin")
    assert dv["co_proxy_moi_truong"] is True and "MATKHAU" not in json.dumps(dv)


def test_cung_duong_bo_qua_thoi_diem_do():
    a = mang.dau_van_mang(_lenh_gia({"-n get": "  interface: en0\n"}), "darwin")
    b = dict(a, luc="khác")
    assert mang.cung_duong(a, b) and not mang.cung_duong(a, dict(a, qua_vpn=True))


def test_chay_lenh_that_khong_ton_tai_tra_rong():
    assert mang._chay_lenh(["/khong/co/lenh-nay"]) == ""


# ═════════════ 4. Nguồn hỏng kéo dài ═════════════

LUC = datetime(2026, 9, 29, 13, 0)


def _luot(ngay_truoc: float, **health: str) -> dict:
    return {"id": 0, "luc": LUC - timedelta(days=ngay_truoc), "sources": {n: {"health": h} for n, h in health.items()}}


def _hien_tai(**health: str) -> Dict[str, dict]:
    return {n: {"health": h, "error": 1 if h == "unavailable" else 0, "kieu_duong_mang": {}} for n, h in health.items()}


def test_ca_nejm_hong_ba_tuan_duoc_bao():
    lich_su = [_luot(0.1, feed_nejm="unavailable"), _luot(8, feed_nejm="unavailable"),
               _luot(13, feed_nejm="unavailable"), _luot(22, feed_nejm="unavailable"), _luot(28, feed_nejm="ok")]
    kq = nhkd.tinh_hong_keo_dai(_hien_tai(feed_nejm="unavailable"), lich_su, LUC)
    assert kq["feed_nejm"]["so_luot_lien"] == 5 and kq["feed_nejm"]["so_ngay"] == 22
    assert kq["feed_nejm"]["hong_tu"] == "2026-09-07" and kq["feed_nejm"]["lan_chay_duoc_cuoi"] == "2026-09-01"


def test_nhieu_luot_trong_cung_mot_ngay_khong_phai_hong_keo_dai():
    lich_su = [_luot(h / 24, feed_ecdc="unavailable") for h in (1, 2, 3)] + [_luot(8, feed_ecdc="ok")]
    assert nhkd.tinh_hong_keo_dai(_hien_tai(feed_ecdc="unavailable"), lich_su, LUC) == {}


@pytest.mark.parametrize("cat_chuoi", ["degraded", "ok", "not_queried", "mock", None])
def test_chuoi_dung_o_luot_nguon_khong_phai_unavailable(cat_chuoi):
    luot_cat = _luot(5, feed_x=cat_chuoi) if cat_chuoi else _luot(5)
    lich_su = [_luot(1, feed_x="unavailable"), luot_cat, _luot(10, feed_x="unavailable"),
               _luot(20, feed_x="unavailable")]
    assert nhkd.tinh_hong_keo_dai(_hien_tai(feed_x="unavailable"), lich_su, LUC) == {}


def test_nguong_bien_dung_ba_luot_va_bay_ngay():
    lich_su = [_luot(3, feed_x="unavailable"), _luot(7, feed_x="unavailable")]
    assert nhkd.tinh_hong_keo_dai(_hien_tai(feed_x="unavailable"), lich_su, LUC)["feed_x"]["so_luot_lien"] == 3
    assert nhkd.tinh_hong_keo_dai(_hien_tai(feed_x="unavailable"), lich_su[:1] + [_luot(6.9, feed_x="unavailable")],
                                  LUC) == {}
    assert nhkd.tinh_hong_keo_dai(_hien_tai(feed_x="unavailable"), [_luot(10, feed_x="unavailable")], LUC) == {}


def test_nguon_dang_chay_duoc_khong_bao_va_nguon_moi_khong_co_lan_chay_duoc():
    lich_su = [_luot(4, a="unavailable", b="unavailable"), _luot(9, a="unavailable", b="unavailable")]
    kq = nhkd.tinh_hong_keo_dai(_hien_tai(a="ok", b="unavailable"), lich_su, LUC)
    assert set(kq) == {"b"} and kq["b"]["lan_chay_duoc_cuoi"] is None


def test_ghi_chu_chap_nhan_duoc_gan_kem_khong_loai_bo():
    lich_su = [_luot(4, scopus="unavailable"), _luot(8, scopus="unavailable")]
    kq = nhkd.tinh_hong_keo_dai(_hien_tai(scopus="unavailable"), lich_su, LUC,
                                ghi_chu=["PUBMED_EUTILS_MIRRORED_BY_EUROPEPMC_AND_CROSSREF",
                                         "SCOPUS_BLOCKED_BY_CLOUDFLARE_403_NETWORK_IP"])
    assert kq["scopus"]["da_co_ghi_chu"] == "SCOPUS_BLOCKED_BY_CLOUDFLARE_403_NETWORK_IP"
    assert "đã có ghi chú SCOPUS_BLOCKED" in nhkd.mo_ta_ngan(kq)


def test_gio_co_mui_gio_va_chuoi_iso_deu_nhan():
    hong = {"x": {"health": "unavailable"}}
    lich_su = [{"luc": (LUC - timedelta(days=4)).isoformat(), "sources": hong},
               {"luc": (LUC - timedelta(days=9)).replace(tzinfo=timezone.utc), "sources": hong}]
    kq = nhkd.tinh_hong_keo_dai(_hien_tai(x="unavailable"), lich_su, LUC.replace(tzinfo=timezone.utc))
    assert kq["x"]["so_ngay"] == 9


@pytest.fixture()
def db_rieng(monkeypatch, tmp_path):
    import app.database as db_mod

    monkeypatch.setattr(db_mod, "_engine", None, raising=False)
    monkeypatch.setattr(db_mod, "_SessionLocal", None, raising=False)
    monkeypatch.setattr(settings, "database_url", f"sqlite:///{tmp_path / 'mang_ben_vung.db'}")
    db_mod.init_db()
    yield db_mod
    monkeypatch.setattr(db_mod, "_engine", None, raising=False)
    monkeypatch.setattr(db_mod, "_SessionLocal", None, raising=False)


def _them_luot(db_mod, *, ngay_truoc: float, mode: str = "live", xong: bool = True, stats: Any = None) -> None:
    from app.models import PipelineRun
    with db_mod.session_scope() as s:
        luc = datetime.now(timezone.utc) - timedelta(days=ngay_truoc)
        s.add(PipelineRun(started_at=luc, finished_at=luc + timedelta(minutes=4) if xong else None, mode=mode,
                          status="ok" if xong else "running", stats=stats))


def test_doc_lich_su_chi_lay_luot_live_da_xong_co_so_do_nguon(db_rieng):
    co_nguon = {"source_health": {"sources": {"feed_x": {"health": "unavailable", "error": 1}}}}
    _them_luot(db_rieng, ngay_truoc=1, stats=co_nguon)
    _them_luot(db_rieng, ngay_truoc=2, stats={"source_health": {"status": "NOT_APPLICABLE"}})   # lượt lấy bù
    _them_luot(db_rieng, ngay_truoc=3, stats=co_nguon, mode="mock")
    _them_luot(db_rieng, ngay_truoc=4, stats=co_nguon, xong=False)                             # lượt kẹt «running»
    _them_luot(db_rieng, ngay_truoc=9, stats=co_nguon)
    lich_su = nhkd.doc_lich_su_suc_khoe()
    bay_gio = datetime.now(timezone.utc).replace(tzinfo=None)
    assert [round((bay_gio - luot["luc"]).total_seconds() / 86400) for luot in lich_su] == [1, 9]
    assert lich_su[0]["sources"] == {"feed_x": {"health": "unavailable"}}


def test_gan_mang_va_hong_keo_dai_vao_source_health(monkeypatch, db_rieng):
    co_nguon = {"source_health": {"sources": {"feed_x": {"health": "unavailable"}}}}
    _them_luot(db_rieng, ngay_truoc=3, stats=co_nguon)
    _them_luot(db_rieng, ngay_truoc=8, stats=co_nguon)
    monkeypatch.setattr(ing.mang, "dau_van_mang", lambda: {"qua_vpn": True, "tuyen_mac_dinh": "utun4"})
    sh = {"sources": _hien_tai(feed_x="unavailable"), "mirror_notices": []}
    ing._gan_mang_va_hong_keo_dai(sh, {"qua_vpn": True, "tuyen_mac_dinh": "utun4"}, datetime.now(timezone.utc))
    assert sh["mang"]["qua_vpn"] is True and "mang_cuoi_luot" not in sh
    assert sh["hong_keo_dai"]["feed_x"]["so_luot_lien"] == 3


def test_duong_mang_doi_giua_luot_duoc_ghi(monkeypatch, db_rieng):
    monkeypatch.setattr(ing.mang, "dau_van_mang", lambda: {"qua_vpn": False, "tuyen_mac_dinh": "en0"})
    sh = {"sources": {}, "mirror_notices": []}
    ing._gan_mang_va_hong_keo_dai(sh, {"qua_vpn": True, "tuyen_mac_dinh": "utun4"}, datetime.now(timezone.utc))
    assert sh["mang_cuoi_luot"]["tuyen_mac_dinh"] == "en0"


def test_khong_doc_duoc_lich_su_la_none_khong_phai_rong(monkeypatch):
    monkeypatch.setattr(ing.mang, "dau_van_mang", lambda: {"qua_vpn": None})

    def hong():
        raise RuntimeError("CSDL khoá")
    monkeypatch.setattr(ing.nguon_hong_keo_dai, "doc_lich_su_suc_khoe", hong)
    sh = {"sources": {}, "mirror_notices": []}
    ing._gan_mang_va_hong_keo_dai(sh, {"qua_vpn": None}, datetime.now(timezone.utc))
    assert sh["hong_keo_dai"] is None and sh["hong_keo_dai_loi"] == "RuntimeError"


class _NguonGia:
    def __init__(self, ten: str) -> None:
        self.name, self.endpoint, self.use_mock = ten, f"https://{ten}.example.org/", False

    def search(self, query, clinical_area=None, max_results=20, since_date=None):
        return []


def _ingest_trong(monkeypatch, mock: bool) -> dict:
    monkeypatch.setitem(ing.CLINICAL_AREAS, "Khu thử", ["q1"])
    monkeypatch.setattr(ing, "get_enabled_sources", lambda: [_NguonGia(n) for n in ("pubmed", "europepmc", "crossref")])
    monkeypatch.setattr("app.sources.rss_feed.get_feed_clients", lambda *a, **k: [])
    monkeypatch.setattr(settings, "enable_openfda", False)
    monkeypatch.setattr(settings, "use_mock_sources", mock)
    chan_doan: dict = {}
    ing.ingest_all(max_results_per_query=2, areas=["Khu thử"], diagnostics=chan_doan)
    return chan_doan


def test_luot_live_ghi_dau_van_mang_va_hong_keo_dai(monkeypatch, db_rieng):
    monkeypatch.setattr(ing.mang, "dau_van_mang", lambda: {"qua_vpn": False, "tuyen_mac_dinh": "en0"})
    chan_doan = _ingest_trong(monkeypatch, mock=False)
    assert chan_doan["mang"] == {"qua_vpn": False, "tuyen_mac_dinh": "en0"} and chan_doan["hong_keo_dai"] == {}
    assert chan_doan["loi_duong_mang"] == {}


def test_luot_mock_khong_do_mang_khong_doc_lich_su(monkeypatch, db_rieng):
    def cam(*a, **k):
        raise AssertionError("lượt mock không được đo đường mạng/đọc lịch sử")
    monkeypatch.setattr(ing.mang, "dau_van_mang", cam)
    monkeypatch.setattr(ing.nguon_hong_keo_dai, "doc_lich_su_suc_khoe", cam)
    chan_doan = _ingest_trong(monkeypatch, mock=True)
    assert "mang" not in chan_doan and "hong_keo_dai" not in chan_doan


# ═════════════ 5. Công cụ tools/do_mang_nguon.py ═════════════

def _cong_cu():
    spec = importlib.util.spec_from_file_location("do_mang_nguon_test", ROOT / "tools" / "do_mang_nguon.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.mark.parametrize("phan_hoi, loi, ma_ok, ky_vong", [
    (_PhanHoi(200, "ok"), None, (200,), "OK"),
    (_PhanHoi(400, "{}"), None, (200, 400), "OK"),
    (_PhanHoi(403, TRANG_CLOUDFRONT, TIEU_DE_CLOUDFRONT), None, (200,), "cloudfront-chan"),
    (_PhanHoi(403, TRANG_CLOUDFLARE, {"Server": "cloudflare", "CF-RAY": "x"}), None, (200,), "cloudflare-chan"),
    (_PhanHoi(200, "x", url="https://misuse.ncbi.nlm.nih.gov/error/abuse.shtml"), None, (200,), "ncbi-chan"),
    (_PhanHoi(429, "x"), None, (200,), "HTTP_429"),
    (None, requests.exceptions.ConnectTimeout("x"), (200,), "ket-noi-het-gio"),
    (None, requests.exceptions.ReadTimeout("x"), (200,), "doc-het-gio"),
    (None, ValueError("x"), (200,), "LOI_ValueError"),
])
def test_cong_cu_phan_loai_cung_nhan_voi_engine(phan_hoi, loi, ma_ok, ky_vong):
    assert _cong_cu().phan_loai(phan_hoi, loi, ma_ok) == ky_vong


class _CauHinhGia:
    ncbi_email = "nguoi@example.org"
    ncbi_api_key = "KHOA-NCBI-BIMAT"
    core_api_key = "KHOA-CORE-BIMAT"
    scopus_api_key = "KHOA-SCOPUS-BIMAT"


def test_cong_cu_scopus_chi_do_khi_xin_va_khong_lo_khoa(monkeypatch):
    mod = _cong_cu()
    monkeypatch.setattr(mod, "dau_van_mang", lambda: {"qua_vpn": True})
    goi: List[str] = []

    def goi_gia(url, params, headers):
        goi.append(url)
        return _PhanHoi(200, "ok", url=url), None
    kq = mod.do(_CauHinhGia(), co_scopus=False, goi=goi_gia)
    assert not any("elsevier" in u for u in goi) and any("api.core.ac.uk" in u for u in goi)
    kq2 = mod.do(_CauHinhGia(), co_scopus=True, goi=goi_gia)
    assert any("elsevier" in u for u in goi)
    for ket_qua in (kq, kq2):
        assert "BIMAT" not in json.dumps(ket_qua) and all(v["ket_qua"] == "OK" for v in ket_qua["nguon"].values())


def test_cong_cu_so_sanh_hai_duong():
    mod = _cong_cu()
    a = {"mang": {"qua_vpn": True, "tuyen_mac_dinh": "utun4", "vpn_dang_noi": ["Kaspersky VPN"]},
         "nguon": {"NCBI": {"ket_qua": "OK"}, "ECDC": {"ket_qua": "cloudfront-chan"}, "S2": {"ket_qua": "HTTP_429"}}}
    b = {"mang": {"qua_vpn": False, "tuyen_mac_dinh": "en0"},
         "nguon": {"NCBI": {"ket_qua": "ncbi-chan"}, "ECDC": {"ket_qua": "OK"}, "S2": {"ket_qua": "HTTP_429"}}}
    ra = "\n".join(mod.so_sanh(a, b))
    assert "CHỈ chạy được trên đường A: NCBI (B: ncbi-chan)" in ra
    assert "CHỈ chạy được trên đường B: ECDC (A: cloudfront-chan)" in ra
    assert "Hỏng trên cả hai: S2 (A: HTTP_429, B: HTTP_429)" in ra


def test_cong_cu_so_sanh_tep_hong_tra_ma_2(tmp_path, capsys):
    hong = tmp_path / "hong.json"
    hong.write_text("{khong phai json", encoding="utf-8", newline="\n")
    assert _cong_cu().main(["--so-sanh", str(hong), str(hong)]) == 2
