export const navItems = [
  { href: "/", label: "Tong quan" },
  { href: "/command-center", label: "Dieu phoi" },
  { href: "/programs", label: "Chuong trinh" },
  { href: "/mvp-01", label: "MVP-01" },
  { href: "/dashboard/doctor", label: "Bac si" },
  { href: "/dashboard/nurse", label: "Dieu duong" },
  { href: "/dashboard/quality", label: "Chat luong" },
  { href: "/patients", label: "Nguoi benh" },
  { href: "/appointments", label: "Hen" },
  { href: "/visits/prep", label: "Chuan bi kham" },
  { href: "/visits/initial", label: "Kham lan dau" },
  { href: "/visits/follow-up", label: "Tai kham" },
  { href: "/medications", label: "Thuoc" },
  { href: "/labs", label: "Xet nghiem" },
  { href: "/care-plans", label: "Care plan" },
  { href: "/tasks", label: "Task" },
  { href: "/referrals", label: "Chuyen tuyen" },
  { href: "/handouts", label: "Loi dan A5" },
  { href: "/risk/red", label: "Nguy co do" },
  { href: "/overdue", label: "Qua han" },
  { href: "/admin/rules", label: "Rules" },
  { href: "/admin/templates", label: "Templates" },
  { href: "/admin/sop", label: "SOP" },
  { href: "/admin/users", label: "Nguoi dung" },
  { href: "/admin/audit", label: "Audit" },
  { href: "/admin/settings", label: "Cai dat" }
];
