#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SINH / KIỂM mirror `.codex/agents/` của repo y khoa từ `.claude/agents/*.md` (01/10/2026).

VÌ SAO CÓ. Codex nạp agent riêng của dự án từ `.codex/agents/*.toml` (tài liệu OpenAI «Subagents»: mỗi tệp
TOML phải có `name`, `description`, `developer_instructions`). Repo này TRACK mirror đó từ commit 20660c0
(08/09/2026, theo yêu cầu bác sĩ) nhưng KHÔNG có công cụ sinh: bộ sinh `tools/sync_agents_to_codex.py`
nằm ở REPO GỐC và chỉ ghi vào thư mục của repo gốc. Đo 01/10/2026 trên nhánh mặc định: kỳ vọng 84 tệp ·
khớp 3 · lệch nội dung 79 (cả 50/50 agent) · thiếu 2 · 0 tệp lệch chỉ do nhãn. Mirror commit ngày 08/09
vốn là ảnh chụp sinh từ nguồn GIỮA THÁNG 7 (README còn QUADAS-2, «Ba cổng nghiên cứu»…), và không chốt
nào canh: hook pre-commit chỉ băm `.claude/agents`, chốt BH107 của repo gốc chỉ so `.claude/agents`.

NHÃN ĐƯỜNG DẪN CỐ ĐỊNH `.codex/agents`. Bộ sinh gốc viết lại chuỗi `.claude/agents` trong thân tệp thành
nhãn của thư mục đích; trên Mac (hệ tệp không phân biệt hoa/thường) nó gộp hai đích và lấy nhãn
`.Codex/agents`, trên Linux ghi cả hai. Bản TRACK chỉ có MỘT thư mục `.codex/agents` (chữ thường), còn
CI/Codex Cloud chạy Linux — ở đó `.Codex/agents/...` trỏ vào thư mục KHÔNG tồn tại. Vì vậy công cụ này
luôn dùng `.codex/agents`, trên mọi máy, để bản sinh trên Mac và trên Linux trùng nhau từng byte.

PHẦN DỰNG chép ĐÚNG NGỮ NGHĨA từ `tools/sync_agents_to_codex.py` của repo gốc (parse_frontmatter,
toml_quote, rewrite_paths, render_agent, render_infra) — kể cả dòng đầu «Generated by
tools/sync_agents_to_codex.py…» — để CI đơn-repo (không có repo gốc) vẫn sinh/kiểm được, mà nội dung ra
TRÙNG BYTE với bộ sinh gốc. Hai bản được đối chiếu chéo ở hai nơi: `tests/test_mirror_codex_agents.py`
(khi tìm thấy repo gốc) và mục BH143 trong `tools/chot_hoi_quy_bai_hoc.py` của repo gốc (mỗi lần mở
phiên trên máy thật). Sửa bộ sinh gốc mà không sửa bản này theo thì hai chốt đó đỏ.

Dùng:
    python3 tools/sinh_mirror_codex.py           # KIỂM (mặc định) — mã 0 khớp · 1 lệch · 2 thiếu nguồn
    python3 tools/sinh_mirror_codex.py --ghi     # sinh lại mirror từ .claude/agents/*.md

KHÔNG sửa tay `.codex/agents/*`. Tệp MỒ CÔI (nguồn đã xoá/đổi tên) công cụ chỉ BÁO, không tự xoá — gỡ bằng
`git rm`. Tệp mới sinh ra phải được `git add` (`.gitignore` đã mở riêng `.codex/agents/`).
Cần bác sĩ kiểm chứng.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11 (vd ~/.ebm-venv 3.9 trên Mac)
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]

for _luong in (sys.stdout, sys.stderr):
    try:
        _luong.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

REPO = Path(__file__).resolve().parents[1]
NGUON = REPO / ".claude" / "agents"
DICH = REPO / ".codex" / "agents"
NHAN = ".codex/agents"

FRONTMATTER_RE = re.compile(r"\A---\n(?P<meta>.*?)\n---\n?(?P<body>.*)\Z", re.DOTALL)


@dataclass(frozen=True)
class AgentSpec:
    """Một agent đọc từ frontmatter của `.claude/agents/<tên>.md`."""

    name: str
    description: str
    body: str
    source_path: Path


def parse_frontmatter(path: Path) -> AgentSpec:
    """Đọc frontmatter YAML đơn giản (khoá: giá trị một dòng) — cùng luật với bộ sinh gốc."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise ValueError(f"{path} khong co YAML frontmatter")

    meta: dict[str, str] = {}
    for raw_line in match.group("meta").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"{path}: dong frontmatter khong hop le: {raw_line!r}")
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        meta[key.strip()] = value

    name = meta.get("name", "").strip()
    description = meta.get("description", "").strip()
    if not name or not description:
        raise ValueError(f"{path}: thieu name hoac description")
    if path.stem != name:
        raise ValueError(f"{path}: filename != name ({path.stem!r} != {name!r})")
    return AgentSpec(name=name, description=description, body=match.group("body").rstrip() + "\n",
                     source_path=path)


def nguon_agent(nguon: Path = NGUON) -> list[Path]:
    """Tệp agent: mọi `*.md` trừ README.md và sổ hạ tầng `_*.md`."""
    return sorted(p for p in nguon.glob("*.md") if p.name != "README.md" and not p.name.startswith("_"))


def nguon_ha_tang(nguon: Path = NGUON) -> list[Path]:
    """Sổ hạ tầng chép nguyên (viết lại đường dẫn): README.md và `_*.md`."""
    return sorted(p for p in nguon.glob("*.md") if p.name == "README.md" or p.name.startswith("_"))


def toml_quote(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\b", "\\b")
        .replace("\t", "\\t")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def rewrite_paths(text: str, nhan: str) -> str:
    return (
        text.replace(".claude/agents", nhan)
        .replace("`.claude/agents", f"`{nhan}")
        .replace(" .claude/agents", f" {nhan}")
    )


def render_agent(spec: AgentSpec, nhan: str = NHAN) -> str:
    body = rewrite_paths(spec.body, nhan)
    return (
        "# Generated by tools/sync_agents_to_codex.py. Edit .claude/agents/*.md, then rerun.\n"
        f"name = {toml_quote(spec.name)}\n"
        f"description = {toml_quote(spec.description)}\n"
        "developer_instructions = '''\n"
        f"{body}"
        "'''\n"
    )


def render_infra(path: Path, nhan: str = NHAN) -> str:
    text = rewrite_paths(path.read_text(encoding="utf-8"), nhan)
    if path.name == "README.md":
        # Viết lại đường dẫn xong thì trả câu «nơi biên tập chính» về `.claude/agents` — như bộ sinh gốc.
        text = text.replace(f"`{nhan}/*.md` là bản biên tập chính", "`.claude/agents/*.md` là bản biên tập chính")
        text = text.replace(f"sửa/thêm agent ở `{nhan}`", "sửa/thêm agent ở `.claude/agents`")
    return (
        "<!-- Generated by tools/sync_agents_to_codex.py. "
        "Edit .claude/agents/*.md, then rerun. -->\n"
        f"{text.rstrip()}\n"
    )


def ban_ky_vong(nguon: Path = NGUON, nhan: str = NHAN) -> dict[str, str]:
    """Tên tệp → nội dung kỳ vọng của mirror, sinh từ `nguon` với nhãn `nhan`."""
    tep: dict[str, str] = {}
    for p in nguon_agent(nguon):
        spec = parse_frontmatter(p)
        tep[f"{spec.name}.toml"] = render_agent(spec, nhan)
    for p in nguon_ha_tang(nguon):
        tep[p.name] = render_infra(p, nhan)
    return tep


def _tep_mirror(dich: Path) -> set[str]:
    """Tệp đang có trong mirror mà Codex/agent đọc tới: `*.toml` và `*.md` (bỏ rác như .DS_Store)."""
    if not dich.is_dir():
        return set()
    return {p.name for p in dich.iterdir() if p.is_file() and p.suffix in (".toml", ".md")}


def kiem(nguon: Path = NGUON, dich: Path = DICH, nhan: str = NHAN) -> list[str]:
    """Danh sách lỗi (rỗng = mirror khớp bản sinh). Kiểm cả hai chiều + TOML hợp lệ cho Codex."""
    ky_vong = ban_ky_vong(nguon, nhan)
    hien_co = _tep_mirror(dich)
    loi: list[str] = []
    for ten in sorted(ky_vong):
        duong = dich / ten
        if ten not in hien_co:
            loi.append(f"THIẾU {nhan}/{ten}")
        elif duong.read_text(encoding="utf-8") != ky_vong[ten]:
            loi.append(f"LỆCH {nhan}/{ten}")
    for ten in sorted(hien_co - set(ky_vong)):
        loi.append(f"MỒ CÔI {nhan}/{ten} (nguồn .claude/agents không còn — gỡ bằng git rm)")
    if tomllib is not None:
        for ten in sorted(t for t in hien_co if t.endswith(".toml")):
            try:
                du_lieu = tomllib.loads((dich / ten).read_text(encoding="utf-8"))
            except Exception as e:  # noqa: BLE001 — TOML hỏng nào cũng là lỗi Codex không nạp được
                loi.append(f"TOML HỎNG {nhan}/{ten}: {e}")
                continue
            if du_lieu.get("name") != ten[: -len(".toml")]:
                loi.append(f"TÊN SAI {nhan}/{ten}: name={du_lieu.get('name')!r}")
            for khoa in ("description", "developer_instructions"):
                if not du_lieu.get(khoa):
                    loi.append(f"THIẾU KHOÁ {khoa} trong {nhan}/{ten}")
    return loi


def ghi(nguon: Path = NGUON, dich: Path = DICH, nhan: str = NHAN) -> list[str]:
    """Ghi mọi tệp kỳ vọng còn khác; trả danh sách tệp đã đổi. KHÔNG xoá tệp mồ côi."""
    dich.mkdir(parents=True, exist_ok=True)
    da_doi: list[str] = []
    for ten, noi_dung in ban_ky_vong(nguon, nhan).items():
        duong = dich / ten
        cu = duong.read_text(encoding="utf-8") if duong.exists() else None
        if cu != noi_dung:
            duong.write_text(noi_dung, encoding="utf-8", newline="\n")
            da_doi.append(ten)
    return da_doi


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Sinh/kiểm mirror .codex/agents từ .claude/agents/*.md (repo y khoa).")
    ap.add_argument("--ghi", action="store_true", help="sinh lại mirror (mặc định chỉ kiểm, không ghi)")
    ap.add_argument("--check", action="store_true", help="chỉ kiểm (mặc định) — giữ cho quen tay với bộ sinh gốc")
    a = ap.parse_args(argv)

    if not NGUON.is_dir():
        print(f"LỖI: không thấy thư mục nguồn {NGUON}", file=sys.stderr)
        return 2
    if a.ghi:
        da_doi = ghi()
        print(f"Đã sinh mirror {NHAN}: {len(da_doi)} tệp đổi")
        for ten in da_doi:
            print(f"  {NHAN}/{ten}")
    loi = kiem()
    if loi:
        print(f"Mirror {NHAN}: LỆCH ({len(loi)} lỗi) — sinh lại: python3 tools/sinh_mirror_codex.py --ghi")
        for dong in loi:
            print(f"  - {dong}")
        return 1
    so_agent = len(nguon_agent())
    print(f"Mirror {NHAN}: KHỚP — {so_agent} agent + {len(nguon_ha_tang())} sổ hạ tầng sinh từ .claude/agents")
    if tomllib is None:
        print("  (⚪ chưa kiểm cú pháp TOML: Python thiếu tomllib/tomli)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
